/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/viki/Desktop/CPG/src/cpg/msg/cpg_pos.msg
 *
 */


#ifndef CPG_MESSAGE_CPG_POS_H
#define CPG_MESSAGE_CPG_POS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cpg
{
template <class ContainerAllocator>
struct cpg_pos_
{
  typedef cpg_pos_<ContainerAllocator> Type;

  cpg_pos_()
    : cpg_x_joint_angles()
    , cpg_y_joint_angles()  {
    }
  cpg_pos_(const ContainerAllocator& _alloc)
    : cpg_x_joint_angles(_alloc)
    , cpg_y_joint_angles(_alloc)  {
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _cpg_x_joint_angles_type;
  _cpg_x_joint_angles_type cpg_x_joint_angles;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _cpg_y_joint_angles_type;
  _cpg_y_joint_angles_type cpg_y_joint_angles;




  typedef boost::shared_ptr< ::cpg::cpg_pos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cpg::cpg_pos_<ContainerAllocator> const> ConstPtr;

}; // struct cpg_pos_

typedef ::cpg::cpg_pos_<std::allocator<void> > cpg_pos;

typedef boost::shared_ptr< ::cpg::cpg_pos > cpg_posPtr;
typedef boost::shared_ptr< ::cpg::cpg_pos const> cpg_posConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cpg::cpg_pos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cpg::cpg_pos_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cpg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'cpg': ['/home/viki/Desktop/CPG/src/cpg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cpg::cpg_pos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cpg::cpg_pos_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cpg::cpg_pos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cpg::cpg_pos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cpg::cpg_pos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cpg::cpg_pos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cpg::cpg_pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2fff63fc5abef0741cd1ffa24a1ff65e";
  }

  static const char* value(const ::cpg::cpg_pos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2fff63fc5abef074ULL;
  static const uint64_t static_value2 = 0x1cd1ffa24a1ff65eULL;
};

template<class ContainerAllocator>
struct DataType< ::cpg::cpg_pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cpg/cpg_pos";
  }

  static const char* value(const ::cpg::cpg_pos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cpg::cpg_pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] cpg_x_joint_angles\n\
float64[] cpg_y_joint_angles\n\
\n\
";
  }

  static const char* value(const ::cpg::cpg_pos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cpg::cpg_pos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cpg_x_joint_angles);
      stream.next(m.cpg_y_joint_angles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct cpg_pos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cpg::cpg_pos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cpg::cpg_pos_<ContainerAllocator>& v)
  {
    s << indent << "cpg_x_joint_angles[]" << std::endl;
    for (size_t i = 0; i < v.cpg_x_joint_angles.size(); ++i)
    {
      s << indent << "  cpg_x_joint_angles[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.cpg_x_joint_angles[i]);
    }
    s << indent << "cpg_y_joint_angles[]" << std::endl;
    for (size_t i = 0; i < v.cpg_y_joint_angles.size(); ++i)
    {
      s << indent << "  cpg_y_joint_angles[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.cpg_y_joint_angles[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CPG_MESSAGE_CPG_POS_H
