; Auto-generated. Do not edit!


(cl:in-package cpg-srv)


;//! \htmlinclude ModifyParameters-request.msg.html

(cl:defclass <ModifyParameters-request> (roslisp-msg-protocol:ros-message)
  ((major_ax
    :reader major_ax
    :initarg :major_ax
    :type cl:float
    :initform 0.0)
   (minor_ax
    :reader minor_ax
    :initarg :minor_ax
    :type cl:float
    :initform 0.0)
   (coup_strength
    :reader coup_strength
    :initarg :coup_strength
    :type cl:float
    :initform 0.0)
   (limit_cycle
    :reader limit_cycle
    :initarg :limit_cycle
    :type cl:float
    :initform 0.0)
   (forward_velocity
    :reader forward_velocity
    :initarg :forward_velocity
    :type cl:float
    :initform 0.0)
   (curvature
    :reader curvature
    :initarg :curvature
    :type cl:float
    :initform 0.0)
   (x_offset
    :reader x_offset
    :initarg :x_offset
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (y_offset
    :reader y_offset
    :initarg :y_offset
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (coupling_1
    :reader coupling_1
    :initarg :coupling_1
    :type (cl:vector cl:integer)
   :initform (cl:make-array 0 :element-type 'cl:integer :initial-element 0))
   (coupling_2
    :reader coupling_2
    :initarg :coupling_2
    :type (cl:vector cl:integer)
   :initform (cl:make-array 0 :element-type 'cl:integer :initial-element 0))
   (coupling_3
    :reader coupling_3
    :initarg :coupling_3
    :type (cl:vector cl:integer)
   :initform (cl:make-array 0 :element-type 'cl:integer :initial-element 0))
   (coupling_4
    :reader coupling_4
    :initarg :coupling_4
    :type (cl:vector cl:integer)
   :initform (cl:make-array 0 :element-type 'cl:integer :initial-element 0))
   (coupling_5
    :reader coupling_5
    :initarg :coupling_5
    :type (cl:vector cl:integer)
   :initform (cl:make-array 0 :element-type 'cl:integer :initial-element 0))
   (coupling_6
    :reader coupling_6
    :initarg :coupling_6
    :type (cl:vector cl:integer)
   :initform (cl:make-array 0 :element-type 'cl:integer :initial-element 0)))
)

(cl:defclass ModifyParameters-request (<ModifyParameters-request>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ModifyParameters-request>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ModifyParameters-request)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cpg-srv:<ModifyParameters-request> is deprecated: use cpg-srv:ModifyParameters-request instead.")))

(cl:ensure-generic-function 'major_ax-val :lambda-list '(m))
(cl:defmethod major_ax-val ((m <ModifyParameters-request>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cpg-srv:major_ax-val is deprecated.  Use cpg-srv:major_ax instead.")
  (major_ax m))

(cl:ensure-generic-function 'minor_ax-val :lambda-list '(m))
(cl:defmethod minor_ax-val ((m <ModifyParameters-request>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cpg-srv:minor_ax-val is deprecated.  Use cpg-srv:minor_ax instead.")
  (minor_ax m))

(cl:ensure-generic-function 'coup_strength-val :lambda-list '(m))
(cl:defmethod coup_strength-val ((m <ModifyParameters-request>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cpg-srv:coup_strength-val is deprecated.  Use cpg-srv:coup_strength instead.")
  (coup_strength m))

(cl:ensure-generic-function 'limit_cycle-val :lambda-list '(m))
(cl:defmethod limit_cycle-val ((m <ModifyParameters-request>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cpg-srv:limit_cycle-val is deprecated.  Use cpg-srv:limit_cycle instead.")
  (limit_cycle m))

(cl:ensure-generic-function 'forward_velocity-val :lambda-list '(m))
(cl:defmethod forward_velocity-val ((m <ModifyParameters-request>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cpg-srv:forward_velocity-val is deprecated.  Use cpg-srv:forward_velocity instead.")
  (forward_velocity m))

(cl:ensure-generic-function 'curvature-val :lambda-list '(m))
(cl:defmethod curvature-val ((m <ModifyParameters-request>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cpg-srv:curvature-val is deprecated.  Use cpg-srv:curvature instead.")
  (curvature m))

(cl:ensure-generic-function 'x_offset-val :lambda-list '(m))
(cl:defmethod x_offset-val ((m <ModifyParameters-request>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cpg-srv:x_offset-val is deprecated.  Use cpg-srv:x_offset instead.")
  (x_offset m))

(cl:ensure-generic-function 'y_offset-val :lambda-list '(m))
(cl:defmethod y_offset-val ((m <ModifyParameters-request>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cpg-srv:y_offset-val is deprecated.  Use cpg-srv:y_offset instead.")
  (y_offset m))

(cl:ensure-generic-function 'coupling_1-val :lambda-list '(m))
(cl:defmethod coupling_1-val ((m <ModifyParameters-request>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cpg-srv:coupling_1-val is deprecated.  Use cpg-srv:coupling_1 instead.")
  (coupling_1 m))

(cl:ensure-generic-function 'coupling_2-val :lambda-list '(m))
(cl:defmethod coupling_2-val ((m <ModifyParameters-request>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cpg-srv:coupling_2-val is deprecated.  Use cpg-srv:coupling_2 instead.")
  (coupling_2 m))

(cl:ensure-generic-function 'coupling_3-val :lambda-list '(m))
(cl:defmethod coupling_3-val ((m <ModifyParameters-request>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cpg-srv:coupling_3-val is deprecated.  Use cpg-srv:coupling_3 instead.")
  (coupling_3 m))

(cl:ensure-generic-function 'coupling_4-val :lambda-list '(m))
(cl:defmethod coupling_4-val ((m <ModifyParameters-request>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cpg-srv:coupling_4-val is deprecated.  Use cpg-srv:coupling_4 instead.")
  (coupling_4 m))

(cl:ensure-generic-function 'coupling_5-val :lambda-list '(m))
(cl:defmethod coupling_5-val ((m <ModifyParameters-request>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cpg-srv:coupling_5-val is deprecated.  Use cpg-srv:coupling_5 instead.")
  (coupling_5 m))

(cl:ensure-generic-function 'coupling_6-val :lambda-list '(m))
(cl:defmethod coupling_6-val ((m <ModifyParameters-request>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cpg-srv:coupling_6-val is deprecated.  Use cpg-srv:coupling_6 instead.")
  (coupling_6 m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ModifyParameters-request>) ostream)
  "Serializes a message object of type '<ModifyParameters-request>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'major_ax))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'minor_ax))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'coup_strength))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'limit_cycle))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'forward_velocity))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'curvature))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'x_offset))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'x_offset))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'y_offset))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'y_offset))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'coupling_1))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    ))
   (cl:slot-value msg 'coupling_1))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'coupling_2))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    ))
   (cl:slot-value msg 'coupling_2))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'coupling_3))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    ))
   (cl:slot-value msg 'coupling_3))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'coupling_4))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    ))
   (cl:slot-value msg 'coupling_4))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'coupling_5))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    ))
   (cl:slot-value msg 'coupling_5))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'coupling_6))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    ))
   (cl:slot-value msg 'coupling_6))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ModifyParameters-request>) istream)
  "Deserializes a message object of type '<ModifyParameters-request>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'major_ax) (roslisp-utils:decode-single-float-bits bits)))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'minor_ax) (roslisp-utils:decode-single-float-bits bits)))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'coup_strength) (roslisp-utils:decode-single-float-bits bits)))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'limit_cycle) (roslisp-utils:decode-single-float-bits bits)))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'forward_velocity) (roslisp-utils:decode-single-float-bits bits)))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'curvature) (roslisp-utils:decode-single-float-bits bits)))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'x_offset) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'x_offset)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'y_offset) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'y_offset)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'coupling_1) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'coupling_1)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296)))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'coupling_2) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'coupling_2)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296)))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'coupling_3) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'coupling_3)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296)))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'coupling_4) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'coupling_4)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296)))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'coupling_5) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'coupling_5)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296)))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'coupling_6) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'coupling_6)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296)))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ModifyParameters-request>)))
  "Returns string type for a service object of type '<ModifyParameters-request>"
  "cpg/ModifyParametersRequest")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ModifyParameters-request)))
  "Returns string type for a service object of type 'ModifyParameters-request"
  "cpg/ModifyParametersRequest")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ModifyParameters-request>)))
  "Returns md5sum for a message object of type '<ModifyParameters-request>"
  "b77231e4a9814c4335488a7d53be3d5c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ModifyParameters-request)))
  "Returns md5sum for a message object of type 'ModifyParameters-request"
  "b77231e4a9814c4335488a7d53be3d5c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ModifyParameters-request>)))
  "Returns full string definition for message of type '<ModifyParameters-request>"
  (cl:format cl:nil "float32 major_ax~%float32 minor_ax~%float32 coup_strength~%float32 limit_cycle~%float32 forward_velocity~%float32 curvature~%float64[] x_offset~%float64[] y_offset~%int32[] coupling_1~%int32[] coupling_2~%int32[] coupling_3~%int32[] coupling_4~%int32[] coupling_5~%int32[] coupling_6~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ModifyParameters-request)))
  "Returns full string definition for message of type 'ModifyParameters-request"
  (cl:format cl:nil "float32 major_ax~%float32 minor_ax~%float32 coup_strength~%float32 limit_cycle~%float32 forward_velocity~%float32 curvature~%float64[] x_offset~%float64[] y_offset~%int32[] coupling_1~%int32[] coupling_2~%int32[] coupling_3~%int32[] coupling_4~%int32[] coupling_5~%int32[] coupling_6~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ModifyParameters-request>))
  (cl:+ 0
     4
     4
     4
     4
     4
     4
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'x_offset) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'y_offset) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'coupling_1) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'coupling_2) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'coupling_3) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'coupling_4) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'coupling_5) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'coupling_6) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ModifyParameters-request>))
  "Converts a ROS message object to a list"
  (cl:list 'ModifyParameters-request
    (cl:cons ':major_ax (major_ax msg))
    (cl:cons ':minor_ax (minor_ax msg))
    (cl:cons ':coup_strength (coup_strength msg))
    (cl:cons ':limit_cycle (limit_cycle msg))
    (cl:cons ':forward_velocity (forward_velocity msg))
    (cl:cons ':curvature (curvature msg))
    (cl:cons ':x_offset (x_offset msg))
    (cl:cons ':y_offset (y_offset msg))
    (cl:cons ':coupling_1 (coupling_1 msg))
    (cl:cons ':coupling_2 (coupling_2 msg))
    (cl:cons ':coupling_3 (coupling_3 msg))
    (cl:cons ':coupling_4 (coupling_4 msg))
    (cl:cons ':coupling_5 (coupling_5 msg))
    (cl:cons ':coupling_6 (coupling_6 msg))
))
;//! \htmlinclude ModifyParameters-response.msg.html

(cl:defclass <ModifyParameters-response> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass ModifyParameters-response (<ModifyParameters-response>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ModifyParameters-response>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ModifyParameters-response)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cpg-srv:<ModifyParameters-response> is deprecated: use cpg-srv:ModifyParameters-response instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ModifyParameters-response>) ostream)
  "Serializes a message object of type '<ModifyParameters-response>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ModifyParameters-response>) istream)
  "Deserializes a message object of type '<ModifyParameters-response>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ModifyParameters-response>)))
  "Returns string type for a service object of type '<ModifyParameters-response>"
  "cpg/ModifyParametersResponse")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ModifyParameters-response)))
  "Returns string type for a service object of type 'ModifyParameters-response"
  "cpg/ModifyParametersResponse")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ModifyParameters-response>)))
  "Returns md5sum for a message object of type '<ModifyParameters-response>"
  "b77231e4a9814c4335488a7d53be3d5c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ModifyParameters-response)))
  "Returns md5sum for a message object of type 'ModifyParameters-response"
  "b77231e4a9814c4335488a7d53be3d5c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ModifyParameters-response>)))
  "Returns full string definition for message of type '<ModifyParameters-response>"
  (cl:format cl:nil "~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ModifyParameters-response)))
  "Returns full string definition for message of type 'ModifyParameters-response"
  (cl:format cl:nil "~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ModifyParameters-response>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ModifyParameters-response>))
  "Converts a ROS message object to a list"
  (cl:list 'ModifyParameters-response
))
(cl:defmethod roslisp-msg-protocol:service-request-type ((msg (cl:eql 'ModifyParameters)))
  'ModifyParameters-request)
(cl:defmethod roslisp-msg-protocol:service-response-type ((msg (cl:eql 'ModifyParameters)))
  'ModifyParameters-response)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ModifyParameters)))
  "Returns string type for a service object of type '<ModifyParameters>"
  "cpg/ModifyParameters")