/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/viki/Desktop/CPG/src/cpg/srv/ModifyParameters.srv
 *
 */


#ifndef CPG_MESSAGE_MODIFYPARAMETERS_H
#define CPG_MESSAGE_MODIFYPARAMETERS_H

#include <ros/service_traits.h>


#include <cpg/ModifyParametersRequest.h>
#include <cpg/ModifyParametersResponse.h>


namespace cpg
{

struct ModifyParameters
{

typedef ModifyParametersRequest Request;
typedef ModifyParametersResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ModifyParameters
} // namespace cpg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cpg::ModifyParameters > {
  static const char* value()
  {
    return "b77231e4a9814c4335488a7d53be3d5c";
  }

  static const char* value(const ::cpg::ModifyParameters&) { return value(); }
};

template<>
struct DataType< ::cpg::ModifyParameters > {
  static const char* value()
  {
    return "cpg/ModifyParameters";
  }

  static const char* value(const ::cpg::ModifyParameters&) { return value(); }
};


// service_traits::MD5Sum< ::cpg::ModifyParametersRequest> should match 
// service_traits::MD5Sum< ::cpg::ModifyParameters > 
template<>
struct MD5Sum< ::cpg::ModifyParametersRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cpg::ModifyParameters >::value();
  }
  static const char* value(const ::cpg::ModifyParametersRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cpg::ModifyParametersRequest> should match 
// service_traits::DataType< ::cpg::ModifyParameters > 
template<>
struct DataType< ::cpg::ModifyParametersRequest>
{
  static const char* value()
  {
    return DataType< ::cpg::ModifyParameters >::value();
  }
  static const char* value(const ::cpg::ModifyParametersRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cpg::ModifyParametersResponse> should match 
// service_traits::MD5Sum< ::cpg::ModifyParameters > 
template<>
struct MD5Sum< ::cpg::ModifyParametersResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cpg::ModifyParameters >::value();
  }
  static const char* value(const ::cpg::ModifyParametersResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cpg::ModifyParametersResponse> should match 
// service_traits::DataType< ::cpg::ModifyParameters > 
template<>
struct DataType< ::cpg::ModifyParametersResponse>
{
  static const char* value()
  {
    return DataType< ::cpg::ModifyParameters >::value();
  }
  static const char* value(const ::cpg::ModifyParametersResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CPG_MESSAGE_MODIFYPARAMETERS_H
