(cl:in-package cpg-srv)
(cl:export '(MAJOR_AX-VAL
          MAJOR_AX
          MINOR_AX-VAL
          MINOR_AX
          COUP_STRENGTH-VAL
          COUP_STRENGTH
          LIMIT_CYCLE-VAL
          LIMIT_CYCLE
          FORWARD_VELOCITY-VAL
          FORWARD_VELOCITY
          CURVATURE-VAL
          CURVATURE
          X_OFFSET-VAL
          X_OFFSET
          Y_OFFSET-VAL
          Y_OFFSET
          COUPLING_1-VAL
          COUPLING_1
          COUPLING_2-VAL
          COUPLING_2
          COUPLING_3-VAL
          COUPLING_3
          COUPLING_4-VAL
          COUPLING_4
          COUPLING_5-VAL
          COUPLING_5
          COUPLING_6-VAL
          COUPLING_6
))